WITH SALES_AMOUNT AS (
SELECT CUSTOMER_ID, SUM(TOTAL_AMOUNT) as TOTAL_SPENT_2023 from TRANSFORMED_SALES_DATA
WHERE ORDER_YEAR = 2023
GROUP BY CUSTOMER_ID
ORDER BY SUM(TOTAL_AMOUNT) DESC
LIMIT 5)
SELECT S.CUSTOMER_ID, C.NAME, S.TOTAL_SPENT_2023 from SALES_AMOUNT S
JOIN RAW_CUSTOMERS_DATA C ON S.CUSTOMER_ID = C.ID
ORDER BY S.TOTAL_SPENT_2023 DESC