SELECT S.CUSTOMER_ID, C.NAME, SUM(S.TOTAL_AMOUNT) as TOTAL_SPENT_2023 from TRANSFORMED_SALES_DATA S
JOIN RAW_CUSTOMERS_DATA C ON S.CUSTOMER_ID = C.ID
WHERE ORDER_YEAR = 2023
GROUP BY CUSTOMER_ID, C.NAME
ORDER BY SUM(TOTAL_AMOUNT) DESC
LIMIT 5